### ISSUE TITLE
Hexdump doesn't consider negative characters

### ISSUE THREAD

**Issue by eze210** [eldipa/tiburoncin#1]
When the first bit from a byte is 1, the hexdump is being printed preppending 0xffffff (because it's a signed char)
The code should either use unsigned characters, or mask each byte with & 0xff
I can't push a branch to send you a PR, btw :)

**Comment by eldipa** [comment]
Wow, that's fun. It seems that when we print a signed byte `printf` promotes the signed byte to a signed integers which it is printed as you mentioned.

I changed the format string from `%02x` to `%02hhx` to avoid the promotion. The use of a mask would work too.

The real fix should be using unsigned chars in the first place.

**Comment by eldipa** [comment]
Offtopic: you need to do a fork and do a PR from there
